trigger: none

pool:
  name: LinuxDinD

parameters:
  - name: build_images
    displayName: Docker Build & Push
    type: boolean
    default: false

  - name: aws
    displayName: AWS Push
    type: boolean
    default: false

  - name: product
    displayName: Select product config
    type: string
    default: 'smartfactory'
    values:
      - smartfactory
      - iot-gateway

  - name: customer
    displayName: Select customer config
    type: string
    default: 'atr'
    values:
      - atr
      - umsicht

variables:
  - group: 'AWS Upload'
  - group: 'Keycloak Customer Config'

stages:
  # ============================================
  # Stage: Build & Push Docker Images
  # ============================================
  - stage: BuildImages
    displayName: 'Build Images'
    condition: eq('${{ parameters.build_images }}', true)
    jobs:
      - job: BuildAndPush
        displayName: 'Build & Push'
        steps:
          - bash: task docker:build:keycloak
            displayName: 'Build Keycloak'

          - bash: task docker:push:keycloak
            displayName: 'Push Keycloak'

          - bash: task docker:push:keycloak-cli
            displayName: 'Push Keycloak CLI'

          - bash: task aws:push
            displayName: 'AWS Push'
            env:
              AWS_PREFIX: $(AWSPrefix)
            condition: eq('${{ parameters.aws }}', true)

  # ============================================
  # Stage: Build Config & Publish Artifact
  # ============================================
  - stage: BuildConfig
    displayName: 'Build Config'
    jobs:
      - job: BuildAndPublish
        displayName: 'Build & Publish'
        steps:
          # --- Smartfactory (base) ---
          - bash: task config:build:smartfactory
            displayName: 'Build smartfactory'
            condition: and(eq('${{ parameters.product }}', 'smartfactory'), eq('${{ parameters.customer }}', 'atr'))

          # --- Smartfactory + Umsicht ---
          - bash: |
              git config --global http.https://atrtfs01.atr.local.extraheader "AUTHORIZATION: Bearer ${SYSTEM_ACCESSTOKEN}"
              task config:build:smartfactory:umsicht
              git config --global --unset http.https://atrtfs01.atr.local.extraheader || true
            displayName: 'Build smartfactory:umsicht'
            condition: and(eq('${{ parameters.product }}', 'smartfactory'), eq('${{ parameters.customer }}', 'umsicht'))
            env:
              CUSTOMER_CONFIG_REPO_URL: $(CustomerConfigRepoUrl)
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)

          # --- IoT-Gateway (base) ---
          - bash: task config:build:iot-gateway
            displayName: 'Build iot-gateway'
            condition: and(eq('${{ parameters.product }}', 'iot-gateway'), eq('${{ parameters.customer }}', 'atr'))

          # Copy deployment files
          - task: CopyFiles@2
            displayName: 'Copy deployment files'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: |
                config/merged/**
                scripts/add-userprofile.sh
              TargetFolder: '$(Build.ArtifactStagingDirectory)/keycloak'
              flattenFolders: false

          # Publish artifact
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifacts'
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'keycloak'
              publishLocation: 'Container'