name: keycloak

services:
  keycloak-cli:
    image: ${REGISTRY}/keycloak-config-cli:${TAG_KEYCLOAK}
    container_name: keycloak-cli
    restart: "no"
    environment:
      KEYCLOAK_URL: https://keycloak:8443
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KC_ADMIN_PASSWORD:-admin}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "120s"
      KEYCLOAK_SSLVERIFY: "false"
      IMPORT_PATH: /config
      IMPORT_VARSUBSTITUTION_ENABLED: "true"
      DHOSTNAME: ${DHOSTNAME}
      PORT_GATEWAY: ${PORT_GATEWAY}
      GATEWAY_SECRET: ${GATEWAY_SECRET}
      USER_SECRET: ${USER_SECRET}
      NODE_RED_SECRET: ${NODE_RED_SECRET}
    volumes:
      - ./config/merged:/config:ro
    networks:
      - keycloak

networks:
  keycloak:
    driver: bridge