name: keycloak

services:
  keycloak-cli:
    image: ${REGISTRY:-atrdocker01.atr.local:7444}/keycloak-config-cli:latest-${TAG_KEYCLOAK:-26.1.0}
    container_name: keycloak-cli
    restart: "no"
    environment:
      KEYCLOAK_URL: https://keycloak:8443
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KC_ADMIN_PASSWORD:-admin}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "120s"
      KEYCLOAK_SSLVERIFY: "false"
      IMPORT_PATH: /config
      IMPORT_VARSUBSTITUTION_ENABLED: "true"
      DHOSTNAME: ${DHOSTNAME:-innomes-dev-vm.atr.local}
      PORT_GATEWAY: ${PORT_GATEWAY:-443}
      GATEWAY_SECRET: ${GATEWAY_SECRET:-your-gateway-secret}
      USER_SECRET: ${USER_SECRET:-your-user-secret}
      NODE_RED_SECRET: ${NODE_RED_SECRET:-your-nodered-secret}
    volumes:
      - ./config/merged:/config:ro
    networks:
      - keycloak

networks:
  keycloak:
    driver: bridge