version: "3"
dotenv: ['.env']

vars:
  REGISTRY: '{{.REGISTRY | default "atrdocker01.atr.local:7444"}}'
  TAG_KEYCLOAK: '{{.TAG_KEYCLOAK | default "26.1.0"}}'

tasks:
  # ============================================
  # Config Build
  # ============================================

  config:build:smartfactory:
    desc: Build realm config for smartfactory (base)
    cmds:
      - scripts/build-config.sh smartfactory

  config:build:smartfactory:umsicht:
    desc: Build realm config for smartfactory + umsicht
    cmds:
      - scripts/build-config.sh smartfactory umsicht

  # ============================================
  # Config Import
  # ============================================

  config:import:
    desc: Import merged realm config into running Keycloak
    cmds:
      - ./scripts/add-userprofile.sh smartfactory
      - docker compose -f compose.keycloak-cli.yaml up

  # ============================================
  # Docker: Keycloak
  # ============================================

  docker:build:keycloak:
    desc: Build Keycloak image
    cmds:
      - |
        docker build \
          -t {{.REGISTRY}}/keycloak:{{.TAG_KEYCLOAK}} \
          --build-arg KC_VERSION={{.TAG_KEYCLOAK}} \
          --label "git.commit.hash=${BUILD_SOURCEVERSION:-local}" \
          --label "git.commit.branch=${BUILD_SOURCEBRANCHNAME:-local}" \
          .

  docker:push:keycloak:
    desc: Push Keycloak image to registry
    cmds:
      - docker push {{.REGISTRY}}/keycloak:{{.TAG_KEYCLOAK}}

  # ============================================
  # Docker: Keycloak CLI
  # ============================================

  docker:push:keycloak-cli:
    desc: Pull, tag and push Keycloak Config CLI
    cmds:
      - docker pull adorsys/keycloak-config-cli:latest-{{.TAG_KEYCLOAK}}
      - docker tag adorsys/keycloak-config-cli:latest-{{.TAG_KEYCLOAK}} {{.REGISTRY}}/keycloak-config-cli:latest-{{.TAG_KEYCLOAK}}
      - docker push {{.REGISTRY}}/keycloak-config-cli:latest-{{.TAG_KEYCLOAK}}

  # ============================================
  # AWS Push
  # ============================================

  aws:push:
    desc: Push both images to AWS
    cmds:
      - /home/ubuntu/bin/aws-upload.sh keycloak {{.AWS_PREFIX}} {{.REGISTRY}}/keycloak {{.TAG_KEYCLOAK}}
      - /home/ubuntu/bin/aws-upload.sh keycloak-config-cli {{.AWS_PREFIX}} {{.REGISTRY}}/keycloak-config-cli latest-{{.TAG_KEYCLOAK}}

  # ============================================
  # Development
  # ============================================

  dev:up:
    desc: Start docker stack without orphans
    cmds:
      - docker compose up -d --remove-orphans

  dev:down:
    desc: Stop docker stack
    cmds:
      - docker compose down

  # ============================================
  # Utilities
  # ============================================

  check:
    desc: Check dependencies
    cmds:
      - scripts/check-dependencies.sh